//
// This file is generated by parsec_rdl 0.0.38 2016-01-04T12:01:04Z
// Please DO NOT edit directly; changes could be overwritten.
//
package com.example.parsec_generated;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

//
// ResourceContext
//
public interface ResourceContext {
    public HttpServletRequest request();
    public HttpServletResponse response();
    public void authenticate();
    public void authorize(String action, String resource, String trustedDomain);
}
