//
// This file is generated by parsec_rdl 0.0.38 2016-01-04T12:01:04Z
// Please DO NOT edit directly; changes could be overwritten.
//
package com.example.parsec_generated;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.glassfish.hk2.utilities.binding.AbstractBinder;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.jetty.JettyHttpContainerFactory;
import org.glassfish.jersey.servlet.ServletContainer;

public class SampleServer {
    SampleHandler handler;

    public SampleServer(SampleHandler handler) {
        this.handler = handler;
    }

    public void run(int port) {
        try {
            Server server = new Server(port);
            ServletContextHandler handler = new ServletContextHandler();
            handler.setContextPath("");
            ResourceConfig config = new ResourceConfig(SampleResources.class).register(new Binder());
            handler.addServlet(new ServletHolder(new ServletContainer(config)), "/*");
            server.setHandler(handler);
            server.start();
            server.join();
        } catch (Exception e) {
            System.err.println("*** " + e);
        }
    }

    class Binder extends AbstractBinder {
        @Override
        protected void configure() {
            bind(handler).to(SampleHandler.class);
        }
    }
}
