//
// This file is generated by parsec_rdl 0.0.38 2016-01-04T12:01:04Z
// Please DO NOT edit directly; changes could be overwritten.
//
package com.example.parsec_generated;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.ws.rs.container.AsyncResponse;

//
// SampleHandler is the interface that the service implementation must implement
//
public interface SampleHandler { 
    public User getUser(ResourceContext context, Integer id);
    public String postUser(ResourceContext context, User user);
    public String putUser(ResourceContext context, Integer id, User user);
    public ResourceContext newResourceContext(HttpServletRequest request, HttpServletResponse response);
}
