//
// This file is generated by parsec_rdl 0.0.38 2016-01-04T12:01:04Z
// Please DO NOT edit directly; changes could be overwritten.
//

package com.example.parsec_generated;

import java.util.List;
import java.util.Map;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

//
// User -
//
public final class User implements java.io.Serializable {

    @NotNull(
        groups = {
            ParsecValidationGroups.Insert.class
        }
    )
    @Size(
        min=3,
        max=5,
        groups = {
            ParsecValidationGroups.Update.class,
            ParsecValidationGroups.Insert.class
        }
    )
    private String name;

    @NotNull(
        groups = {
            ParsecValidationGroups.Update.class
        }
    )
    @Size(
        min=4,
        groups = {
            ParsecValidationGroups.Update.class,
            ParsecValidationGroups.Insert.class
        }
    )
    private String occupation;

    private int age;

    @Null(
        groups = {
            ParsecValidationGroups.Insert.class
        }
    )
    private String id;

    @Digits(
        integer=8,
        fraction=2,
        groups = {
            ParsecValidationGroups.Insert.class,
            ParsecValidationGroups.Update.class
        }
    )
    private Double salary;

    public User() { }

    public String getName() { return name; }

    public String getOccupation() { return occupation; }

    public int getAge() { return age; }

    public String getId() { return id; }

    public Double getSalary() { return salary; }


    public User setName(String name) { this.name = name; return this; }

    public User setOccupation(String occupation) { this.occupation = occupation; return this; }

    public User setAge(int age) { this.age = age; return this; }

    public User setId(String id) { this.id = id; return this; }

    public User setSalary(Double salary) { this.salary = salary; return this; }

    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this, false);
    }

    @Override
    public boolean equals(Object obj) {
        return EqualsBuilder.reflectionEquals(this, obj, false);
    }
}
